In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.distributions import Beta, Dirichlet

import numpy as np

In [ ]:
torch.

In [20]:
d = Dirichlet(torch.rand((1,5)))

In [21]:
d.sample()

tensor([[0.2552, 0.4499, 0.1100, 0.0270, 0.1578]])

In [27]:
b = Beta(torch.tensor([0.3, 0.4, 0.8]), torch.tensor([0.5, 0.3, 0.3]))

In [30]:
??Dirichlet

Init signature: Dirichlet(concentration, validate_args=None)
Source:        
class Dirichlet(ExponentialFamily):
    r"""
    Creates a Dirichlet distribution parameterized by concentration :attr:`concentration`.

    Example::

        >>> m = Dirichlet(torch.tensor([0.5, 0.5]))
        >>> m.sample()  # Dirichlet distributed with concentrarion concentration
        tensor([ 0.1046,  0.8954])

    Args:
        concentration (Tensor): concentration parameter of the distribution
            (often referred to as alpha)
    """
    arg_constraints = {'concentration': constraints.positive}
    support = constraints.simplex
    has_rsample = True

    def __init__(self, concentration, validate_args=None):
        if concentration.dim() < 1:
            raise ValueError("`concentration` parameter must be at least one-dimensional.")
        self.concentration = concentration
        batch_shape, event_shape = concentration.shape[:-1], concentration.shape[-1:]
        super(Dirichlet, self).

In [48]:
device = torch.device('cpu')
if torch.cuda.is_available():
    device = torch.device('cuda')

dim = (20,)
out = (7,)
ls = [6,8,8,4]

layers = []
for i in range(len(ls)):
    layers.append(nn.ReLU())
    layers.append(nn.Linear(ls[i], ls[i + 1]))

layers = [nn.Linear(dim[0], ls[0])]
for i in range(len(ls) - 1):
    layers.append(nn.ReLU())
    layers.append(nn.Linear(ls[i], ls[i + 1]))
layers.append(nn.ReLU())
layers.append(nn.Linear(ls[-1], out[0]))

model = nn.Sequential(*layers).to(device)

print(model)
print(device)

Sequential(
  (0): Linear(in_features=20, out_features=6, bias=True)
  (1): ReLU()
  (2): Linear(in_features=6, out_features=8, bias=True)
  (3): ReLU()
  (4): Linear(in_features=8, out_features=8, bias=True)
  (5): ReLU()
  (6): Linear(in_features=8, out_features=4, bias=True)
  (7): ReLU()
  (8): Linear(in_features=4, out_features=7, bias=True)
)
cpu


In [53]:
model(torch.randn((20,)))

tensor([ 0.2590,  0.4158,  0.1676, -0.5395,  0.4768, -0.4109,  0.3691],
       grad_fn=<AddBackward0>)

In [95]:
import torch
import torch.nn as nn

if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
        
def init_weights(layer: nn.Module):
    if type(layer) == nn.Linear:
        torch.nn.init.kaiming_uniform_(layer.weight, nonlinearity='relu')
        layer.bias.data.fill_(0.)

def build_mlp(in_dim: tuple, out_dim: tuple, layers: list):
    net = [nn.Linear(in_dim[0], layers[0])]
    
    for i in range(len(layers) - 1):
        net.append(nn.ReLU())
        net.append(nn.Linear(layers[i], layers[i + 1]))
        
    net.append(nn.ReLU())
    net.append(nn.Linear(layers[-1], out_dim[0]))

    net = nn.Sequential(*net).to(device)
    net.apply(init_weights)
    
    return net

In [96]:
mlp = build_mlp(in_dim=(20,), out_dim=(7,), layers=[8,7,6,5])

In [97]:
list(mlp.parameters())

[Parameter containing:
 tensor([[ 0.5254,  0.1563,  0.4073, -0.4238, -0.4611,  0.4745, -0.4721, -0.4046,
           0.0309, -0.1514,  0.5128, -0.3894,  0.0888, -0.5222,  0.0327, -0.2393,
          -0.2331, -0.4002,  0.5146,  0.2501],
         [ 0.0864,  0.1765, -0.2520, -0.1480,  0.3296, -0.2804, -0.0099,  0.2843,
          -0.1035,  0.4085, -0.2743,  0.1129,  0.2098,  0.3242,  0.2360, -0.4926,
           0.2998,  0.2409, -0.2786,  0.5271],
         [ 0.2701,  0.0844, -0.1469, -0.1306,  0.4427,  0.0418, -0.1324, -0.4709,
           0.5132,  0.1400, -0.1024,  0.2705, -0.5034,  0.1209, -0.4951,  0.3939,
           0.0933,  0.1042, -0.0394, -0.3291],
         [ 0.4559, -0.2152,  0.1740, -0.1812,  0.0946, -0.4688,  0.2741,  0.0629,
           0.2609,  0.3315,  0.4681, -0.1700,  0.2243, -0.0414,  0.3478,  0.1238,
          -0.5217, -0.2124,  0.4387, -0.2533],
         [-0.4276,  0.0029, -0.1156,  0.0586,  0.0050, -0.0126, -0.2282, -0.3918,
           0.5331,  0.3120,  0.2338, -0.5439, -0.46

In [98]:
mlp.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.5254,  0.1563,  0.4073, -0.4238, -0.4611,  0.4745, -0.4721, -0.4046,
                        0.0309, -0.1514,  0.5128, -0.3894,  0.0888, -0.5222,  0.0327, -0.2393,
                       -0.2331, -0.4002,  0.5146,  0.2501],
                      [ 0.0864,  0.1765, -0.2520, -0.1480,  0.3296, -0.2804, -0.0099,  0.2843,
                       -0.1035,  0.4085, -0.2743,  0.1129,  0.2098,  0.3242,  0.2360, -0.4926,
                        0.2998,  0.2409, -0.2786,  0.5271],
                      [ 0.2701,  0.0844, -0.1469, -0.1306,  0.4427,  0.0418, -0.1324, -0.4709,
                        0.5132,  0.1400, -0.1024,  0.2705, -0.5034,  0.1209, -0.4951,  0.3939,
                        0.0933,  0.1042, -0.0394, -0.3291],
                      [ 0.4559, -0.2152,  0.1740, -0.1812,  0.0946, -0.4688,  0.2741,  0.0629,
                        0.2609,  0.3315,  0.4681, -0.1700,  0.2243, -0.0414,  0.3478,  0.1238,
                       -0.5217, -0

In [100]:
from collections import namedtuple
Transition = namedtuple('Transition',
                        ('state', 'action', 'next_state', 'reward'))

In [106]:
memory = []
memory.append(Transition(np.random.random((10,10)), np.random.random((10)), np.random.random((10,10)), 2))

In [120]:
import random
from collections import namedtuple

# Reference:
# https://github.com/pytorch/tutorials/blob/master/intermediate_source/reinforcement_q_learning.py

Transition = namedtuple("Transition", "observation action reward next_observation")


class Memory(object):
    """
    Enables experience replay
    """
    def __init__(self, capacity: int):
        """
        :param capacity: max memory capacity
        """
        self.capacity = capacity
        self.memory = []
        self.position = 0

    def push(self, observation, action, reward, next_observation):
        """
        Push a trajectory to memory
        :param observation: current observation
        :param action: agent action
        :param reward: received reward
        :param next_observation: observation at next time step
        """

        assert observation.shape != next_observation.shape, "observation space shapes do not match"

        if len(self.memory) < self.capacity:
            self.memory.append(Transition(observation, action, reward, next_observation))
        else:
            self.memory[self.position].append(Transition(observation, action, reward, next_observation))
            self.position = (self.position + 1) % self.capacity

    def sample(self, batch_size: int):
        """

        :param batch_size:
        :return: sampled trajectories
        """
        return random.sample(self.memory, batch_size)

    def __len__(self):
        return len(self.memory)


In [121]:
mem = Memory(100)

In [122]:
mem.push(np.random.random((2,2)), np.random.random((2)), np.random.random((2,2)), np.random.random((1)))
mem.push(np.random.random((2,2)), np.random.random((2)), np.random.random((2,2)), np.random.random((1)))
mem.push(np.random.random((2,2)), np.random.random((2)), np.random.random((2,2)), np.random.random((1)))

In [124]:
mem.sample(2)

[Transition(observation=array([[0.74815739, 0.07167716],
        [0.65015886, 0.31415404]]), action=array([0.19004682, 0.56775847]), reward=array([[0.34857276, 0.83995573],
        [0.9458837 , 0.94466579]]), next_observation=array([0.90552869])),
 Transition(observation=array([[0.41245144, 0.29057312],
        [0.13261959, 0.52315308]]), action=array([0.97653912, 0.42170304]), reward=array([[0.08164602, 0.05557822],
        [0.74678752, 0.03081152]]), next_observation=array([0.83388901]))]

In [150]:
dis = Dirichlet(torch.tensor([0.5, 1, 10]))

In [151]:
dis.sample()

tensor([0.0955, 0.3455, 0.5590])

In [135]:
dis.mean

tensor([0.1429, 0.2857, 0.5714])

In [136]:
dis.mean

tensor([0.1429, 0.2857, 0.5714])

In [152]:
dis.log_prob(torch.tensor([0.0064, 0.4796, 0.5141]))

tensor(-0.5445)

In [184]:
import torch
import torch.nn as nn
from torch.distributions import Dirichlet

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def init_weights(layer: nn.Module):
    if type(layer) == nn.Linear:
        torch.nn.init.kaiming_uniform_(layer.weight, nonlinearity='relu')
        layer.bias.data.fill_(0.)


def build_mlp(in_dim: tuple, out_dim: tuple, layers: list):
    net = [nn.Linear(in_dim[0], layers[0])]

    for i in range(len(layers) - 1):
        net.append(nn.ReLU())
        net.append(nn.Linear(layers[i], layers[i + 1]))

    net.append(nn.ReLU())
    net.append(nn.Linear(layers[-1], out_dim[0]))

    net = nn.Sequential(*net).to(device)
    net.apply(init_weights)

    return net


class Policy(nn.Module):
    def __init__(self, observation_space: tuple, action_space: tuple, layers: list):
        super(Policy, self).__init__()
        self.network = build_mlp(
            in_dim=observation_space,
            out_dim=action_space,
            layers=layers
        )


class DirichletPolicy(Policy):
    def __init__(self, observation_space: tuple, action_space: tuple, layers: list):
        super(DirichletPolicy, self).__init__(observation_space, action_space, layers)
        self.distribution = None
        self.action = None

    def forward(self, observation):
        alphas = self.network(observation)
        self.distribution = Dirichlet(alphas)
        self.action = self.distribution.sample()
        return self.action

    def log_prob(self):
        # return the negative log probability
        return self.distribution.log_prob(self.action)

In [179]:
policy = DirichletPolicy((100,), (7,), [2,6,9])

In [180]:
action = policy(torch.randn((100,)))

In [181]:
action.sum()

tensor(1.0000)

In [183]:
policy.log_prob()

tensor(124.2491, grad_fn=<SubBackward0>)

In [187]:
policy.eval()

<bound method Module.eval of DirichletPolicy(
  (network): Sequential(
    (0): Linear(in_features=100, out_features=2, bias=True)
    (1): ReLU()
    (2): Linear(in_features=2, out_features=6, bias=True)
    (3): ReLU()
    (4): Linear(in_features=6, out_features=9, bias=True)
    (5): ReLU()
    (6): Linear(in_features=9, out_features=7, bias=True)
  )
)>

In [188]:
policy.train()

DirichletPolicy(
  (network): Sequential(
    (0): Linear(in_features=100, out_features=2, bias=True)
    (1): ReLU()
    (2): Linear(in_features=2, out_features=6, bias=True)
    (3): ReLU()
    (4): Linear(in_features=6, out_features=9, bias=True)
    (5): ReLU()
    (6): Linear(in_features=9, out_features=7, bias=True)
  )
)

In [190]:
policy.state_dict()

OrderedDict([('network.0.weight',
              tensor([[ 0.1047, -0.0829, -0.2417, -0.0845, -0.1319,  0.0605, -0.0187,  0.0951,
                       -0.2140,  0.1294, -0.1223,  0.1449, -0.1496,  0.0485, -0.1724,  0.1933,
                        0.1885,  0.2406, -0.0942, -0.0636, -0.1179,  0.1168, -0.0126, -0.0495,
                        0.1039,  0.1290, -0.2123,  0.0454,  0.1745,  0.0431, -0.0607,  0.0595,
                       -0.1741, -0.0983,  0.0911, -0.0334,  0.2157,  0.1914, -0.2386, -0.0555,
                        0.2364,  0.0490,  0.1988,  0.1315, -0.2406,  0.1786,  0.1634, -0.1098,
                        0.0706,  0.0476, -0.1254, -0.0632, -0.1843, -0.1998, -0.1401, -0.0061,
                       -0.1829, -0.1978, -0.0995,  0.2069,  0.1733,  0.0674,  0.0447, -0.1781,
                       -0.1650,  0.0552, -0.1142, -0.2422,  0.0887, -0.1734,  0.1787,  0.0654,
                        0.0573, -0.0845,  0.2118, -0.2348, -0.0912, -0.2367,  0.2066,  0.0823,
                